apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: ux-github-actions
  namespace: ux-github-actions
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: ux-github-actions
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: ux-github-actions
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: ux-github-actions-
      labels:
        build.appstudio.openshift.io/application: ux-github-actions
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: ux-github-actions
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: ux-github-actions
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/actions-to-appstudio
      - name: output-image
        value: quay.io/jduimovich0/ux-github-actions:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: ux-github-actions/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
